### ISSUE TITLE
[보류]전투 기능 추가

### ISSUE THREAD

**Issue by promet99** [Van0614/mudgame#2]
[전체 보류]

전투는 2~3가지 공격으로 하면 될 것 같음.
가령 공격력이 10이라면, 
10의 데미지를 90%로 주는 공격1
15의 데미지를 75%로 주는 공격2
20의 데미지를 45%로 주는 공격3

이렇게 하고, (10+레벨*2)% 만큼 크리티컬 공격!으로 해서 공격력 50% 상승

**Comment by promet99** [comment]
순서도

1. 맵의 특정 위치에서 몬스터를 만남.
2. 여러가지 공격 중에서 한 가지 선택해서 사용.
3. 공격의 결과 확인 및 내가 몬스터한테 받은 공격 보기. (뭔가 크리티컬이라면 화면에 효과를??)
4. 2~3 반복하다, 체력 20% 미만 또는 10회 이상 반복시(몇번 반복했는지 저장해야할듯) 도망가기도 액션에 추가

**Comment by Kyunghwan-Shin** [comment]
기본스펙사항 (괄호 안은 추가스펙사항) 구현


//TODO 

- [x] 1. 온라인에서 플레이 가능

- [x] 2. 로그인, 회원가입

- [x] 3. 맵파일, 몬스터, 아이템 json 파일 생성 

- [ ] 4. 캐릭터모델 생성
( 인벤토리 / 능력치 클라이언트에서 확인 가능케 / 랜덤 능력치&5번까지 재시도)

- [ ] 5. 캐릭터 이동 시 이벤트 발생하게 하는 코드 : Event 모델 만들어서 '몬스터조우' '아이템획득' '무반응'? 
(어느 셀에서도 랜덤하게 이벤트 발생할 수 있도록 / 체력 회복 이벤트 )

- [ ] 6.  전투 시스템 / 사망 시트템 / 레벨 시스템
(10턴안에 전투가 끝나지 않거나 체력이 20퍼센트 이하로 감소할 경우 도주 선택지 /  사망 시 아이템 랜덤하게 분실)
