### ISSUE TITLE
battleCalculator 쓰는 방법 잘 모르겠어요...

### ISSUE THREAD

**Issue by Van0614** [Van0614/mudgame#5]
const battleCalculator = (attack, defense, accuracy = 1) => {
  const random = Math.random()
  if (random < accuracy) {
    return 0
  } else {
    if (attack - defense > 0) {
      return attack - defense

    } else {
      return 1
    }
  }
}

**Comment by promet99** [comment]
0.7의 정확도를 가진 공격을 하면, 70%확률로 데미지가 들어가고 30% 확률로 아무 일도 일어나지 않아요
